
kind: Namespace
apiVersion: v1
metadata:
  name: vuejs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuejs
  labels:
    app: vuejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuejs
  template:
    metadata:
      labels:
        app: vuejs
    spec:
      containers:
      - name: vuejs
        image: tftest/vuejs
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: vuejs
spec:
  selector:
    app: vuejs
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000